### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by Rahul-Venugopal** [Bartzi/loans#7]
Hi ,

I have created the dataset as per the readme and when I run `train_sheep_localizer.py ` as in following command : 

`python /home/rahul/ActiveShuttle/WSOL/LOANS/loans-master/train_sheep_localizer.py /home/rahul/ActiveShuttle/WSOL/LOANS/Dataset/Localizer/pics_extracted/gt.csv  /home/rahul/ActiveShuttle/WSOL/LOANS/figure_skating/evaluation_dataset/gt.json /home/rahul/ActiveShuttle/WSOL/LOANS/Dataset/Assessor/dataset/images.csv  --target-size 75 100 --batch-size 64   --gpu 0   --learning-rate 1e4   --log-name figure_skating_person  --use-resnet-18 `

I get following error 

```
Traceback (most recent call last):
  File "/home/rahul/ActiveShuttle/WSOL/LOANS/loans-master/train_sheep_localizer.py", line 259, in <module>
    main()
  File "/home/rahul/ActiveShuttle/WSOL/LOANS/loans-master/train_sheep_localizer.py", line 155, in main
    **updater_args
  File "/home/rahul/ActiveShuttle/WSOL/LOANS/loans-master/sheep/sheep_updater.py", line 12, in __init__
    self.n_dis = kwargs.pop('n_dis')
KeyError: 'n_dis'
```

Can anyone please help to find the problem ?

**Comment by Bartzi** [comment]
Hi,

sry that it took me so long to answer. There was an error in the code. I just fixed that. Please get the most recent version of the code and try again. You should not have this problem anymore.

**Comment by Rahul-Venugopal** [comment]
Hi,

Thanks for your support. Will check and let you know.
